# Generated by Django 4.2.2 on 2023-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
