# Generated by Django 4.2 on 2023-05-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="document",
            field=models.CharField(default="123456789X", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producer",
            name="phone",
            field=models.CharField(default="+34123456789", max_length=20),
            preserve_default=False,
        ),
    ]
