# Generated by Django 4.2 on 2023-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0002_producer_document_producer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="biography",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
