# Generated by Django 4.2 on 2023-05-16 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0003_producer_biography"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producer",
            name="phone",
        ),
    ]
