# Generated by Django 4.2.1 on 2023-05-18 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0004_remove_producer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producer",
            name="document",
        ),
    ]
