version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/nginx-docker.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    command: npm run start
    expose:
      - 3000
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: sh ./entrypoint.prod.sh
    expose:
      - 8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./db/.env
volumes:
  postgres_data:
