# Generated by Django 4.2.2 on 2023-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_deleted_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
