# Generated by Django 4.2 on 2023-05-10 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_consumer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_producer",
        ),
    ]
