# Generated by Django 4.2 on 2023-05-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_is_consumer_remove_user_is_producer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/", verbose_name="photo"
            ),
        ),
    ]
