# Generated by Django 4.2 on 2023-05-16 15:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326, verbose_name="location"
            ),
        ),
    ]
