# Generated by Django 4.2.2 on 2023-06-13 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_adminuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUser",
        ),
    ]
