# Generated by Django 4.2.1 on 2023-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="comment",
            new_name="description",
        ),
        migrations.AddField(
            model_name="report",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="target",
            field=models.CharField(
                choices=[
                    ("PRODUCER", "PRODUCER"),
                    ("LISTING", "LISTING"),
                    ("ORDER", "ORDER"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
