# Generated by Django 4.2.1 on 2023-05-24 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0002_rename_comment_report_description_report_is_resolved_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="target",
        ),
    ]
