# Generated by Django 4.2.1 on 2023-05-24 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_remove_report_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
