# Generated by Django 4.2.2 on 2023-06-17 10:20

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("KG", "kilogram"), ("UNIT", "unitary")], max_length=10
                    ),
                ),
                ("price_per_unit", models.PositiveIntegerField()),
                ("g_per_unit", models.PositiveIntegerField(null=True)),
                ("available_quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("ALLOWS_DELIVERY", "allows_delivery"),
                            ("ALLOWS_PICKUP", "allows_pickup"),
                            ("IS_FROZEN", "is_frozen"),
                            ("IS_VEGAN", "is_vegan"),
                            ("IS_SUGAR_FREE", "is_sugar_free"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAllergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.CharField(
                        choices=[
                            ("LACTOSE", "lactose"),
                            ("WHEAT", "wheat"),
                            ("NUTS", "nuts"),
                            ("CELERY", "celery"),
                            ("CRUSTACEANS", "crustaceans"),
                            ("EGG", "egg"),
                            ("FISH", "fish"),
                            ("GLUTEN", "gluten"),
                            ("LUPINS", "lupins"),
                            ("MILK", "milk"),
                            ("MOLLUSKS", "mollusks"),
                            ("MUSTARD", "mustard"),
                            ("PEANUTS", "peanuts"),
                            ("SESAME", "sesame"),
                            ("SOYBEANS", "soybeans"),
                            ("SULPHITES", "sulphites"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergens",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=listings.models.listing_images_directory_path
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
