# Generated by Django 4.2 on 2023-05-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="kg_per_unit",
        ),
        migrations.AddField(
            model_name="listing",
            name="g_per_unit",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="price_per_unit",
            field=models.PositiveIntegerField(),
        ),
    ]
