# Generated by Django 4.2 on 2023-05-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_remove_listing_kg_per_unit_listing_g_per_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="allergens",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="features",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="images",
        ),
        migrations.AddField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listings.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productallergen",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergens",
                to="listings.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="listings.listing",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(
                upload_to="C:\\Users\\andre\\git\\tfg\\server/listings/images/"
            ),
        ),
    ]
