# Generated by Django 4.2 on 2023-05-15 21:38

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_remove_listing_allergens_remove_listing_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(
                upload_to=listings.models.listing_images_directory_path
            ),
        ),
    ]
