# Generated by Django 4.2 on 2023-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_created_at_listing_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="g_per_unit",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
