# Generated by Django 4.2.2 on 2023-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_listing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
