# Generated by Django 4.2.2 on 2023-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CHAT_MESSAGE", "CHAT_MESSAGE"),
                            ("NEW_LISTING", "NEW_LISTING"),
                            ("NEW_REVIEW", "NEW_REVIEW"),
                            ("NEW_LIKE", "NEW_LIKE"),
                            ("REVIEW_ORDER", "REVIEW_ORDER"),
                            ("REMINDER_COMPLETE_PROFILE", "REMINDER_COMPLETE_PROFILE"),
                            ("REPORT_CONFIRMATION", "REPORT_CONFIRMATION"),
                        ],
                        max_length=64,
                    ),
                ),
                ("data", models.JSONField()),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
