# Generated by Django 4.2.1 on 2023-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="receiver",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="category",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CHAT_MESSAGE", "CHAT_MESSAGE"),
                    ("NEW_LISTING", "NEW_LISTING"),
                    ("NEW_REVIEW", "NEW_REVIEW"),
                    ("NEW_LIKE", "NEW_LIKE"),
                    ("REMINDER_REVIEW", "REMINDER_REVIEW"),
                    ("REMINDER_COMPLETE_PROFILE", "REMINDER_COMPLETE_PROFILE"),
                    ("REPORT_CONFIRMATION", "REPORT_CONFIRMATION"),
                ],
                default=1,
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
