# Generated by Django 4.2.1 on 2023-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rename_user_notification_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CHAT_MESSAGE", "CHAT_MESSAGE"),
                    ("NEW_LISTING", "NEW_LISTING"),
                    ("NEW_REVIEW", "NEW_REVIEW"),
                    ("NEW_LIKE", "NEW_LIKE"),
                    ("REVIEW_ORDER", "REVIEW_ORDER"),
                    ("REMINDER_COMPLETE_PROFILE", "REMINDER_COMPLETE_PROFILE"),
                    ("REPORT_CONFIRMATION", "REPORT_CONFIRMATION"),
                ],
                max_length=64,
            ),
        ),
    ]
