# Generated by Django 4.2.2 on 2023-06-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=2000)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT_MESSAGE", "TEXT_MESSAGE"),
                            ("LOCATION_MESSAGE", "LOCATION_MESSAGE"),
                            ("REVIEW_ORDER", "REVIEW_ORDER"),
                            ("REPORT_CONFIRMATION", "REPORT_CONFIRMATION"),
                        ],
                        max_length=64,
                    ),
                ),
                ("read_by_recipient", models.BooleanField(default=False)),
                ("data", models.JSONField(null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
