# Generated by Django 4.2.1 on 2023-05-18 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_listing_g_per_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0002_alter_message_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="initiator",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="receiver",
        ),
        migrations.AddField(
            model_name="conversation",
            name="consumer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convo_starter",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convo_listing",
                to="listings.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="producer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convo_participant",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
