# Generated by Django 4.2.1 on 2023-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_message_data_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
