# Generated by Django 4.2.1 on 2023-05-21 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_listing_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0009_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("consumer", "listing")},
        ),
    ]
