# Generated by Django 4.2.1 on 2023-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0010_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT_MESSAGE", "TEXT_MESSAGE"),
                    ("LOCATION_MESSAGE", "LOCATION_MESSAGE"),
                    ("REVIEW_ORDER", "REVIEW_ORDER"),
                    ("REPORT_CONFIRMATION", "REPORT_CONFIRMATION"),
                ],
                max_length=64,
            ),
        ),
    ]
