# Generated by Django 4.2.1 on 2023-05-23 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0011_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
    ]
