# Generated by Django 4.2.1 on 2023-05-23 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0007_listing_is_active"),
        ("chats", "0012_alter_conversation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("consumer", "listing")},
        ),
    ]
