# Generated by Django 4.2.1 on 2023-05-23 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_listing_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0013_alter_conversation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.listing"
            ),
        ),
    ]
